<?php
/** @var $this \Feast\View */
/** @var $release \Model\Release */
$release = $this->release;
?>
<div id="header_wrap" class="outer">
    <header class="inner">
        <a id="forkme_banner" href="https://github.com/feastframework/framework">View on GitHub</a>
        <div>
            <h1 id="project_title" class="inline-block">FEAST Framework </h1>
            <?php $this->partial('partials/version',['releases' => $this->releases, 'release' => $release], false); ?>
            
        </div>
        <h2 id="project_tagline">Fast, Easy, Agile, Slim, Tested and Trans Fat Free</h2>

    </header>
    
</div>


<!-- MAIN CONTENT -->
<div id="main_content_wrap" class="outer">

    <section id="main_content" class="inner">

        <?= utf8_decode($this->contents); ?>
        <h2>&nbsp;</h2>
        <small>
            Powered by <a href="https://github.com/feastframework/framework">FEAST Framework</a><br />
            See this project at <a href="https://github.com/feastframework/documentation">https://github.com/feastframework/documentation</a>
        </small>
    </section>
</div>
